apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: toy-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      terminationGracePeriodSeconds: 35
      tolerations:
        - key: "node-type"
          operator: "Equal"
          value: "low-power"
          effect: "NoSchedule"
      containers:
        - name: notification-service
          image: localhost:5000/notification-service:202609221016-d9114da
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: shared-config
          env:
            - name: SERVER_PORT
              value: "8082"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 20
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - notification-service    # 换成你实际的app标签值
            topologyKey: kubernetes.io/hostname