# 定义日志格式（放 http 块级别，两个 server 都能用）
log_format main_ext '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" $request_time';

server {
    listen 80;

    # 用户流量，记录
    access_log /var/log/nginx/access.log main_ext;   # 本地存一份（Pod活着的时候在）
    access_log /dev/stdout main_ext;                 # 同时输出到stdout，给Fluent Bit用

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 127.0.0.1:8080;

    access_log off;   # 探针流量，不记录

    location /nginx_status {
        stub_status on;
    }
}