apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: toy-infra
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mysql
  namespace: toy-infra
  labels:
    kubernetes.io/service-name: mysql
addressType: IPv4
ports:
  - name: ""
    port: 3306
    protocol: TCP
endpoints:
  - addresses:
      - "192.168.40.23"