#引入prometheus后，该配置被下面的文件取代
#/home/ziqiao/Documents/homelab-toy-system/infra/k8s/toy-infra/Prometheus-Grafana-Alertmanager/host-exporters-monitoring.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: toy-infra
spec:
  ports:
    - port: 9121
      targetPort: 9121
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: redis-exporter-eps
  namespace: toy-infra
  labels:
    kubernetes.io/service-name: redis-exporter
addressType: IPv4
ports:
  - port: 9121
endpoints:
  - addresses: ["192.168.40.23"]