apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod6
  namespace: scaling-drill
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "lowpower-testing"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:alpine