apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: my-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 8Gi
    class: local-storage
    selector:
      matchLabels:
        app: kafka

# roles: [controller, broker] — 单节点homelab没必要拆两种角色，一个节点身兼两职，等你以后加第二台node才需要拆成独立的NodePool
# storage.class: local-storage — 对应我们之前建的StorageClass
# storage.selector.matchLabels.app: kafka — 对应kafka-pv-0身上打的label，保证精确匹配，不会被以后的ES PV误抢